# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 2.7.18
      uses: actions/setup-python@v3
      with:
        python-version: "2.7.18"
    - name: Install OneFLUX
      run: |
        python -m pip install --upgrade pip
        pip install setuptools==44.1.1 wheel pytest
        # pip install flake8 pytest
        # if [ -f frozen-requirement.txt ]; then pip install -r frozen-requirements.txt; fi
        make
    - name: Get data
      run: |
        mkdir -p ./tests/data/test_input
        mkdir -p ./tests/data/test_output
        # get necessary data
        wget ftp://ftp.fluxdata.org/.ameriflux_downloads/.test/US-ARc_sample_input.zip
        wget ftp://ftp.fluxdata.org/.ameriflux_downloads/.test/US-ARc_sample_output.zip
        unzip US-ARc_sample_input.zip -d ./tests/data/test_input/
        unzip US-ARc_sample_output.zip -d ./tests/data/test_output/
    - name: Run pytest
      run: |
        export PYTHONPATH=/home/runner/work/ONEFlux/ONEFlux:$PYTHONPATH
        pytest tests/python